cloudinary.cloud_name = dea1l3vvu
cloudinary.api_key = 632729326888512
cloudinary.api_secret = lOmmfYvysmFHA1lgmPZRg0hUuZM

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vunguyen.0208200402@gmail.com
spring.mail.password=jaimxeyikyewiufp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

lecturer.info.time.reset.password = 24
lecturer.info.password = ou@123

rabbitmq.exchange.name = emailExchange
rabbitmq.queue.name = emailQueue
rabbitmq.routing.key.name = emailRoutingKey